# This is a basic workflow to help you get started with Actions

name: ci-gcr.io

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull --platform linux/arm64 gcr.io/distroless/static:latest
          docker tag gcr.io/distroless/static:latest cnzf/gcr.io:distroless.static.arm64-latest
          docker pull --platform linux/amd64 gcr.io/distroless/static:latest
          docker tag gcr.io/distroless/static:latest cnzf/gcr.io:distroless.static.amd64-latest

          docker pull gcr.io/oss-fuzz-base/base-image
          docker tag gcr.io/oss-fuzz-base/base-image cnzf/gcr.io:oss-fuzz-base.base-image.latest
          docker pull gcr.io/oss-fuzz-base/base-clang
          docker tag gcr.io/oss-fuzz-base/base-clang cnzf/gcr.io:oss-fuzz-base.base-clang.latest
          docker pull gcr.io/oss-fuzz-base/base-builder
          docker tag gcr.io/oss-fuzz-base/base-builder cnzf/gcr.io:oss-fuzz-base.base-builder.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-go
          docker tag gcr.io/oss-fuzz-base/base-builder-go cnzf/gcr.io:oss-fuzz-base.base-builder-go.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-jvm
          docker tag gcr.io/oss-fuzz-base/base-builder-jvm cnzf/gcr.io:oss-fuzz-base.base-builder-jvm.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-python
          docker tag gcr.io/oss-fuzz-base/base-builder-python cnzf/gcr.io:oss-fuzz-base.base-builder-python.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-rust
          docker tag gcr.io/oss-fuzz-base/base-builder-rust cnzf/gcr.io:oss-fuzz-base.base-builder-rust.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-ruby
          docker tag gcr.io/oss-fuzz-base/base-builder-ruby cnzf/gcr.io:oss-fuzz-base.base-builder-ruby.latest
          docker pull gcr.io/oss-fuzz-base/base-builder-swift
          docker tag gcr.io/oss-fuzz-base/base-builder-swift cnzf/gcr.io:oss-fuzz-base.base-builder-swift.latest
          docker pull gcr.io/oss-fuzz-base/base-runner
          docker tag gcr.io/oss-fuzz-base/base-runner cnzf/gcr.io:oss-fuzz-base.base-runner.latest
          docker pull gcr.io/oss-fuzz-base/base-runner-debug
          docker tag gcr.io/oss-fuzz-base/base-runner-debug cnzf/gcr.io:oss-fuzz-base.base-runner-debug.latest
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push cnzf/gcr.io:distroless.static.arm64-latest
          docker push cnzf/gcr.io:distroless.static.amd64-latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-image.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-clang.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-go.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-jvm.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-python.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-rust.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-ruby.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-builder-swift.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-runner.latest
          docker push cnzf/gcr.io:oss-fuzz-base.base-runner-debug.latest

