# This is a basic workflow to help you get started with Actions

name: CI-ghcr.io

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull --platform linux/amd64 ghcr.io/cross-rs/aarch64-linux-android:0.2.5
          docker tag ghcr.io/cross-rs/aarch64-linux-android:0.2.5 cnzf/ghcr.io:cross-rs.aarch64-linux-android.0.2.5
          docker pull --platform linux/amd64 ghcr.io/slint-ui/slint/armv7-unknown-linux-gnueabihf:latest
          docker tag ghcr.io/slint-ui/slint/armv7-unknown-linux-gnueabihf:latest cnzf/ghcr.io:slint-ui.slint.armv7-unknown-linux-gnueabihf.latest
          docker pull --platform linux/amd64 ghcr.io/slint-ui/slint/x86_64-unknown-linux-gnu:latest
          docker tag ghcr.io/slint-ui/slint/x86_64-unknown-linux-gnu:latest cnzf/ghcr.io:slint-ui.slint.x86_64-unknown-linux-gnu.latest
          docker pull --platform linux/amd64 ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5
          docker tag ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5 cnzf/ghcr.io:cross-rs.x86_64-pc-windows-gnu.0.2.5
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push cnzf/ghcr.io:cross-rs.aarch64-linux-android.0.2.5
          docker push cnzf/ghcr.io:slint-ui.slint.armv7-unknown-linux-gnueabihf.latest
          docker push cnzf/ghcr.io:slint-ui.slint.x86_64-unknown-linux-gnu.latest
          docker push cnzf/ghcr.io:cross-rs.x86_64-pc-windows-gnu.0.2.5

