# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull registry.k8s.io/sig-storage/snapshot-controller:v6.2.2
          docker pull registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
          docker pull registry.k8s.io/sig-storage/csi-resizer:v1.8.0
          docker pull registry.k8s.io/sig-storage/csi-attacher:v4.3.0
          docker pull registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          docker pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
          docker tag registry.k8s.io/sig-storage/snapshot-controller:v6.2.2 cnzf/k8s.io:sig-storage.snapshot-controller.v6.2.2
          docker tag registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2 cnzf/k8s.io:sig-storage.csi-snapshotter.v6.2.2
          docker tag registry.k8s.io/sig-storage/csi-resizer:v1.8.0 cnzf/k8s.io:sig-storage.csi-resizer.v1.8.0
          docker tag registry.k8s.io/sig-storage/csi-attacher:v4.3.0 cnzf/k8s.io:sig-storage.csi-attacher.v4.3.0
          docker tag registry.k8s.io/sig-storage/csi-provisioner:v3.5.0 cnzf/k8s.io:sig-storage.csi-provisioner.v3.5.0
          docker tag registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0 cnzf/k8s.io:sig-storage.csi-node-driver-registrar.v2.8.0
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push cnzf/k8s.io:sig-storage.snapshot-controller.v6.2.2
          docker push cnzf/k8s.io:sig-storage.csi-snapshotter.v6.2.2
          docker push cnzf/k8s.io:sig-storage.csi-resizer.v1.8.0
          docker push cnzf/k8s.io:sig-storage.csi-attacher.v4.3.0
          docker push cnzf/k8s.io:sig-storage.csi-provisioner.v3.5.0
          docker push cnzf/k8s.io:sig-storage.csi-node-driver-registrar.v2.8.0

